### ISSUE TITLE
Buffer corruption (or misrendering) with Fish shell

### ISSUE THREAD

**Issue by augustoborn** [martanne/dvtm#14] opened 2016-01-02 17:36 UTC
Using the latest git versions of fish, dvtm and st, I get the following corruption by just holding down enter:

```
augusto $
augusto $
augusto $
augustoaugusto $
augusto $
augusto $
augusto $
```

This happens very reliably and the corrupted line `augustoaugusto $` does not scroll up unless a new line (anything other than `augusto $`) is added at the bottom (if I call `ls`, for example). When I do, this corrupted line "becomes" a normal line and scrolls up.

If I do call `ls` on a buffer such as the one above and hold down enter, more corrupted lines are generated, and scroll up along with the output of `ls` _until_ that output is out of the viewport. After that, the lines just float there, stuck.

This doesn't seem to happen with bash within dvtm+st, or with fish+st without dvtm. Weird.

**Comment by martanne** [comment] 2016-01-02 21:47
Thanks for the report, I can sort of reproduce the behavior you encountered. Unfortunately I probably won't have time to take a closer look during the near future. This is another bug which could be fixed by [switching to a more conforming terminal emulation component](https://github.com/martanne/dvtm/issues/8#issuecomment-126273153).

**Comment by augustoborn** [comment] 2016-01-04 14:06
I've noticed that st also has different UTF character handling, rolling their own decoder instead of using mbrtowc. Could this be the source of the problem? Or do you think it's unhandled control chars?

**Comment by pickfire** [comment] 2016-01-24 05:39
I don't have this issue, I use git fish, git st and dvtm 0.14, I don't have this problem.

**Comment by pickfire** [comment] 2016-01-24 05:46
I get this problem when I am using git dvtm, when I am not in a home directory, the prompt is slow to display.

**Comment by sshbio** [comment] 2016-02-03 15:41
I had a similar issue for either abduco and dvtm: backspace has the same effect on screen as a space (but not in bash/sh/whatever I tried).

I use st, abduco and dvtm from the git sources.

Apart from these glitches, I like this project!

**Comment by sshbio** [comment] 2016-02-05 14:34
I found the solution to my problem with dvtm, and it was in the readme!

I had to install  the terminfo with the command `tic -s dvtm.info` in the source directory.  I do not know why it was not done, but now it works for me!

**Comment by varmanishant** [comment] 2016-03-14 12:45
My buffer gets corrupt when I use `ncmpcpp`. I get a beep in the terminal as well.
I use `abduoc`, `dvtm` on `termite` and my shell is zsh.

**Comment by Link-Satonaka** [comment] 2016-06-14 05:33
I get buffer corruption with st, and missing terminfo is not the issue. I recently learned dvtm will fix this with a screen redraw, but it's still annoying.

Almost reliably happens when I open vim and navigate the cursor to a direction it cannot go any further. In this example, the cursor was at row 5 column 1. I tried to move the cursor left, but since it is already in column 1 it cannot go any further left. Then this happens: some buffer history or current terminal status bleeds through. Given the context I want to say it's trying to ring an error bell, but failing. This happens all the time in contexts other than vim, but I can easily reproduce it using this method.
![2016-06-14-012817_1280x800_scrot](https://cloud.githubusercontent.com/assets/4342746/16031918/000f75ec-31cf-11e6-8966-607502923cc6.png)

After I redraw the screen, all is well.
![2016-06-14-012820_1280x800_scrot](https://cloud.githubusercontent.com/assets/4342746/16031919/00342216-31cf-11e6-9dfa-dbb0e86d625a.png)

**Comment by Link-Satonaka** [comment] 2016-06-24 06:04
Actually, this is 100% reproducible with 
`echo -e 'line1\nline2'`

dvtm's output of the above is reliably drawn wrong.

**Comment by Link-Satonaka** [comment] 2016-09-29 14:44
Commit https://github.com/martanne/dvtm/commit/2673e9d08aba1dfbd405fb6fa13169fed7ce5c34 seems to have fixed the bug for me! `echo -e 'line1\nline2'` renders properly every time now, and in 5 minutes of testing I was unable to get text to bleed through in vim like I demonstrated above.

Horray! This bug has been a thorn in my side for over a year- glad to see it squashed.

**Comment by martanne** [comment] 2016-09-29 19:09
Thanks. I'm going to close this, feel free to re-open if it reappears.

**Closed by martanne** 2016-09-29 19:09 UTC

**Comment by AeliusSaionji** [comment] 2018-02-01 08:57
Any chance you could release a new minor version of dvtm? It'd be nice to just use the version provided by my distro, rather than working off the git.
